---

- name: PLAY1 - GET HARDWARE DETAILS FROM ROUTERS
  hosts: routers
  connection: local
  gather_facts: false
  
  tasks:
    - name: "run multiple commands and check if version output contains specific version string"
      vyos_command:
        commands:
          - show version
          - show hardware cpu
        wait_for:
          - "result[0] contains 'VyOS 1.1.7'"

- name: PLAY2 - GET HARDWARE DETAILS FROM SWITCHES
  hosts: switches
  # connection: local
  # gather_facts: false
  
  tasks:
    # - debug: var=hostvars['switch']
    # - name: fetch interfaces
    #   fetch: dest=save/{{ansible_hostname}}/interfaces src=/etc/network/interfaces flat=yes

    - name: "do things in Cumulus"
      nclu:
        commands:
          - show configuration commands

          